# permissions for end users to edit devs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-editor-role
rules:
- apiGroups:
  - webapp.dev.cwxstat.io
  resources:
  - devs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.dev.cwxstat.io
  resources:
  - devs/status
  verbs:
  - get
