
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapp.dev.cwxstat.io
  resources:
  - devs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.dev.cwxstat.io
  resources:
  - devs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - webapp.dev.cwxstat.io
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.dev.cwxstat.io
  resources:
  - jobs/status
  verbs:
  - get
